apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: renata-growing-plants-api-hpa
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: renata-growing-plants-api
  targetCPUUtilizationPercentage: 80
