name: Build and Deploy Development Growing Plants Service to GKE Cluster

on:
  push:
    branches: ["dev"]

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GAR_LOCATION: ${{ secrets.GAR_LOCATION }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  REPOSITORY: ${{ secrets.REPOSITORY}}
  IMAGE: ${{ secrets.IMAGE}}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: development

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - id: "setup"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: Docker configuration
        run: |-
          gcloud auth print-access-token \
            --impersonate-service-account ${{ secrets.ACCOUNT }} | docker login \
            -u oauth2accesstoken \
            --password-stdin https://${{ secrets.GAR_LOCATION }}-docker.pkg.dev

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      - name: Build
        run: |-
          docker build \
            --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            .

      - name: Tag Image with Latest
        run: |-
          docker tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA" \
            "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:latest"

      - name: Publish
        run: |-
          docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA"
          docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:latest"

      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      - name: Configure Container Port and Image in Deployment
        run: |-
          sed -i -e 's~ENV_GAR_LOCATION~'"$GAR_LOCATION"'~g' base/dev/deployment.yaml
          sed -i -e 's~ENV_REPOSITORY~'"$REPOSITORY"'~g' base/dev/deployment.yaml
          sed -i -e 's~ENV_IMAGE~'"$IMAGE"'~g' base/dev/deployment.yaml
          sed -i -e 's~ENV_PROJECT_ID~'"$PROJECT_ID"'~g' base/dev/deployment.yaml
          sed -i -e 's~ENV_GITHUB_SHA~'"$GITHUB_SHA"'~g' base/dev/deployment.yaml

      - name: Deploy
        run: |-
          ./kustomize build base/dev | kubectl apply -f -
          kubectl rollout status deployment/renata-growing-plants-api
          kubectl get services -o wide
